language: node_js
cache:
  directories:
    - "node_modules"
script: npm run build
deploy:
  - provider: pages
    local-dir: dist
    github-token: $GITHUB_TOKEN
    skip_cleanup: true
branches:
  only:
    - master
